name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.1.9"]
    env:
      DOCKER_BUILDKIT: 1
      TERRAFORM_VERSION: ${{ matrix.terraform_version }}
    steps:
      - uses: actions/checkout@v2

      - name: Execute cibuild
        run: ./scripts/cibuild

      - name: Execute cipublish
        run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          CR_USER: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
